### ISSUE TITLE
 Failed to connect to ESP8266

### ISSUE THREAD

**Issue by aliaabdouli** [snapcrafters/arduino#16]
I am trying to connect the ESP2866 to arduino Mega, I installed the ESP2866 Board in the board manager. 
I get the following error:

esptool.py v2.8
Serial port COM4
Connecting........_____....._____....._____....._____....._____....._____.....____Traceback (most recent call last):
  File "C:\Users\Alia Abdouli\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4/tools/upload.py", line 65, in <module>
    esptool.main(cmdline)
  File "C:/Users/Alia Abdouli/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool\esptool.py", line 2890, in main
    esp.connect(args.before)
  File "C:/Users/Alia Abdouli/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool\esptool.py", line 483, in connect
    raise FatalError('Failed to connect to %s: %s' % (self.CHIP_NAME, last_error))
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header
_
the selected serial port _
 does not exist or your board is not connected

**Comment by merlijn-sebrechts** [comment]
Hi @aliaabdouli

Unfortunately, I cannot help you with issues of running Arduino on Windows. This bugtracker is for issues with the Snap package of Arduino. Snap packages are "installers" to run software on Ubuntu Linux.

Please create a post in https://forum.arduino.cc/ so the Arduino folks can help you further.
